[devshell]
name = "prometheus-golang"
motd = """{106}NixOS Prometheus exporter development shell{reset}
\n REMEMBER TO RUN {200}destroy{reset} when leaving the shell
"""

packages = [
    "prometheus",
    "gotools",
    "cobra-cli",
    "goreleaser",
    "golangci-lint",
    "tmux"
]

#startup.prometheus.text = "tmux new -s prometheus -d 'prometheus --config.file=$(dirname $0)/prometheus.yml'"
startup.kill_services.text = "alias destroy='tmux kill-session'"
