apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: jsp-githubreleasetracker
spec:
  schedule: "0 */3 * * *"
  jobTemplate:
    metadata:
      name: jsp-githubreleasetracker
    spec:
      template:
        spec:
          serviceAccountName: jsp-githubreleasetracker
          containers:
            - name: githubreleasetracker
              image: eu.gcr.io/jetstack-preflight/jsp-utils # This image is overridden within the Makefile
              imagePullPolicy: IfNotPresent
              env:
                - name: GITHUB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: githubreleasetracker-config
                      key: github_api_key
              resources:
                limits:
                  cpu: 100m
                  memory: 100Mi
                requests:
                  cpu: 100m
                  memory: 100Mi
              command:
                - githubreleasetracker
              args:
                - update
                - --configmap
                - jetstack-releases
                - --configmap-namespace
                - prod-saas
                - --github-org
                - jetstack
                - --kubeconfig
                - ""
          restartPolicy: OnFailure
