project_name: auth0-simple-exporter
before:
  hooks:
    - go mod tidy
builds:
  - id: "linux"
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X "interal/version.version={{.Version}}" -X "interal/version.commit={{.Commit}}" -X "interal/version.date={{.Date}}"
    binary: "{{ .ProjectName }}"
    goos:
      - linux
    goarch:
      - amd64
      - arm64
  - id: "darwin"
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X "interal/version.version={{.Version}}" -X "interal/version.commit={{.Commit}}" -X "interal/version.date={{.Date}}"
    binary: "{{ .ProjectName }}"
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
  - id: "windows"
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X "interal/version.version={{.Version}}" -X "interal/version.commit={{.Commit}}" -X "interal/version.date={{.Date}}"
    binary: "{{ .ProjectName }}"
    goos:
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - id: linux
    format: tar.gz
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: true
    builds:
      - "linux"
  - id: darwin
    format: tar.gz
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: true
    builds:
      - "darwin"
  - id: windows
    format: tar.gz
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: true
    builds:
      - "windows"

checksum:
  name_template: "{{ .ProjectName }}-SHA256SUMS"
  algorithm: sha256
release:
  draft: true
changelog:
  use: github-native
  skip: false

docker_signs:
  - cmd: cosign

    # Command line templateable arguments for the command
    #
    # defaults to `["sign", "--key=cosign.key", "${artifact}@${digest}", "--yes"]`
    args:
      - "sign"
      - "--upload=true"
      - "${artifact}"
      - "--yes" # needed on cosign 2.0.0+

    artifacts: all

    # List of environment variables that will be passed to the signing command as well as the templates.
    #
    # Defaults to empty
    env:
      - FOO=bar
      - HONK=honkhonk

    # By default, the stdout and stderr of the signing cmd are discarded unless GoReleaser is running with `--debug` set.
    # You can set this to true if you want them to be displayed regardless.
    #
    # Default: false.
    # Since: v1.2.
    output: true

kos:
  - working_dir: .
    base_image: gcr.io/distroless/base:nonroot

    # Labels for the image.
    #
    # Defaults to null.
    # Since v1.17.
    labels:
      org.opencontainers.image.source: https://github.com/tfadeyi/auth0-simple-exporter
      org.opencontainers.image.description: "Simple Prometheus exporter for Auth0 log events"
      org.opencontainers.image.licenses: APACHE
      org.opencontainers.image.title: "Auth0 Exporter"
      org.opencontainers.image.vendor: ""
      org.opencontainers.image.authors: "Oluwole Fadeyi"

    # Platforms to build and publish.
    #
    # Defaults to linux/amd64.
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm

    # Tag templates to build and push.
    #
    # Defaults to `latest`.
    tags:
      - latest
      - '{{.Tag}}'

    # Creation time given to the image
    # in seconds since the Unix epoch as a string.
    #
    # Defaults to empty string.
    # Since v1.17.
    creation_time: '{{.CommitTimestamp}}'

    # Creation time given to the files in the kodata directory
    # in seconds since the Unix epoch as a string.
    #
    # Defaults to empty string.
    # Since v1.17.
    ko_data_creation_time: '{{.CommitTimestamp}}'

    # SBOM format to use.
    #
    # Defaults to spdx.
    # Valid options are: spdx, cyclonedx, go.version-m and none.
    sbom: cyclonedx

    # Bare uses a tag on the KO_DOCKER_REPO without anything additional.
    #
    # Defaults to false.
    bare: true

    # Whether to use the base path without the MD5 hash after the repository name.
    #
    # Defaults to false.
    base_import_paths: true
