basePath: /
host: localhost:9301
info:
  contact:
    name: Oluwole Fadeyi (@tfadeyi)
  description: |-
    A simple Prometheus exporter for Auth0 log [events](https://auth0.com/docs/api/management/v2#!/Logs/get_logs),
    which allows you to collect metrics from Auth0 and expose them in a format that can be consumed by Prometheus.
  license:
    name: Apache 2.0
    url: https://github.com/tfadeyi/auth0-simple-exporter/blob/main/LICENSE
  title: Auth0 simple exporter
  version: 0.0.7
paths:
  /metrics:
    get:
      description: Exposes the Auth0 metrics collected by the exporter in a prometheus
        format.
      produces:
      - application/json
      - text/plain; charset=utf-8
      responses: {}
      summary: Auth0 metrics in Prometheus format.
  /probe:
    get:
      description: 'Exposes the exporter''s own metrics, i.e: target_scrape_request_total.'
      produces:
      - application/json
      - text/plain; charset=utf-8
      responses: {}
      summary: Exporter's own metrics for its operations.
swagger: "2.0"
