root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = ["swagger"]
  bin = "./tmp/swagger"
  cmd = "go generate ./... && go build -o ./tmp/swagger ."
  delay = 120
  exclude_dir = ["deploy", "builds", "tmp", "dev", "kodata", "cmd", "pkg/version", "pkg/exporter/metrics", "pkg/swagger", "pkg/client", "pkg/docs", "pkg/logging"]
  exclude_file = ["pkg/exporter/server.go", "pkg/exporter/options.go", "main.go", "pkg/exporter/doc.go"]
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go","md"]
  include_file = ["pkg/exporter/exporter.go","docs/metrics.md"]
  kill_delay = "10s"
  log = "build-errors.log"
  rerun = false
  rerun_delay = 5000
  send_interrupt = true
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
