[[env]]
name = "GOROOT"
value = ""
[[env]]
name = "PC_DISABLE_TUI"
value = "true"
[[env]]
name = "CGO_ENABLED"
value = "0"

[devshell]
name = "prometheus-golang"
motd = """{106}NixOS Prometheus exporter development shell{reset}

Developement commands:
 * generate: runs go generate
 * test: run tests and linting
 * up: startup services
 * down: shutdown services

{250}Links{reset}:
 * {30}go ref{reset}: http://localhost:1313/pkg/github.com/tfadeyi/auth0-simple-exporter/
 * {1}prometheus{reset}: http://localhost:9090/ (run {1}prom{reset} command in your terminal)

\n REMEMBER TO RUN {1}down{reset} BEFORE using CTRL-D!
\n Use CTRL-D to leave the shell
"""

packages = [
    "process-compose", "go", "gotools",
    "prometheus", "moq",
    "goreleaser", "golangci-lint",
    "tmux", "helm-docs",
    "go-swag", "ko",
]

# Profiling & Testing
startup.heap.text = "alias heap='go tool pprof'"

startup.generate.text = "alias generate='process-compose -f ./dev/process-compose.yaml up generate'"
startup.testing.text = "alias test='process-compose -f ./dev/process-compose.yaml'"
startup.services_up.text = "alias up='process-compose -f ./dev/services.yaml up godoc'"
startup.services_down.text = "alias down='process-compose process stop godoc'"
