[[env]]
name = "GOROOT"
value = ""
[[env]]
name = "PC_DISABLE_TUI"
value = "true"
[[env]]
name = "CGO_ENABLED"
value = "0"

[devshell]
name = "prometheus-golang"
motd = """{106}NixOS Prometheus exporter development shell{reset}

Developement commands:
 * generate: runs go generate
 * run-test: run tests and linting
 * up: startup services
 * down: shutdown services
 * fmt: formatter

{250}Links{reset}:
 * {30}go ref{reset}: http://localhost:1313/pkg/github.com/tfadeyi/auth0-simple-exporter/
 * {1}prometheus{reset}: http://localhost:9090/ (run {1}prom{reset} command in your terminal)

\n REMEMBER TO RUN {1}down{reset} BEFORE using CTRL-D!
\n Use CTRL-D to leave the shell
"""

packages = [
    "process-compose", "go", "gotools",
    "prometheus", "moq",
    "goreleaser", "golangci-lint",
    "tmux", "helm-docs",
    "go-swag", "ko", "gnumake"
]

[[commands]]
name = "run-test"
command = """
make test
make lint
KO_DOCKER_REPO=ghcr.io/tfadeyi/auth0-exporter goreleaser check
"""

[[commands]]
name = "fmt"
command = """
make format
"""

[[commands]]
name = "generate"
command = """
make generate
gomod2nix
"""

[[commands]]
name = "up"
command = """
process-compose -f ./dev/services.yaml up godoc
"""

[[commands]]
name = "down"
command = """
process-compose process stop godoc
"""
