# my global config
global:
  scrape_interval: 10s # Set the scrape interval to every 5 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: auth0_exporter
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:9301']
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9301

# Rules and alerts are read from the specified file(s)
rule_files:
  - rules.yml
