# Default values for auth0-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# -- image settings
image:
  repository: ghcr.io/tfadeyi/auth0-simple-exporter
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v0.2.6"

# -- specify credentials if pulling from a customer registry
imagePullSecrets: []
# -- Helm default setting to override release name, leave blank
nameOverride: ""
# -- Helm default setting, use this to shorten install name
fullnameOverride: ""

# -- Exporter's Auth0 client configuration
auth0:
  createSecret: true
  secretName: auth0-credentials
  # -- Auth0 tenant's domain. (i.e: <tenant_name>.eu.auth0.com)
  domain: "<change_me>.eu.auth0.com"
  # -- Auth0 management api static token. (the token can be used instead of client credentials)
  token: ""
  # -- Auth0 management api client-id. (do not set if static token is already set)
  clientId: ""
  # -- Auth0 management api client-secret. (do not set if static token is already set)
  clientSecret: ""

# -- Exporter's configuration
exporter:
  # -- Enabled pprof profiling on the exporter on port :6060. (help: https://jvns.ca/blog/2017/09/24/profiling-go-with-pprof/)
  pprof: false
  namespace: ""
  # -- URL Path under which to expose the collected auth0 metrics.
  metricsEndpoint: "metrics"
  # -- Port where the server will listen.
  port: 9301
  logLevel: info

  # -- Exporter's metrics configuration
  metrics:
    # -- Tenant Users metrics exported by the exporter
    users:
      # -- Stops the exporter from fetching user info from the Auth0 tenant
      disabled: false

  # -- Exporter's TLS configuration
  tls:
    # -- Allow the exporter to use autocert to renew its certificates with letsencrypt.
    # (can only be used if the exporter is publicly accessible by the internet)
    auto: false
    # -- Run exporter without TLS.
    enabled: true
    # -- The different allowed hosts for the exporter. Only works when --tls.auto has been enabled.
    hosts: []
    createSecret: false
    secretKey: ""
    secretName: ""
    # -- The certificate file for the exporter TLS connection.
    certFile: ""
    # -- The key file for the exporter TLS connection.
    keyFile: ""

labels: {}

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 9301


resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
