{{- if .Values.exporter.tls.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.exporter.tls.secretName }}
  labels:
    app.kubernetes.io/name: {{ include "auth0-exporter.name" . }}
    helm.sh/chart: {{ include "auth0-exporter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- if .Values.labels -}}
    {{- .Values.labels | toYaml | nindent 4 }}
    {{- end }}
type: tls
data:
  tls.crt: {{ .Values.exporter.tls.certFile | b64enc | quote }}
  tls.key: {{ .Values.exporter.tls.keyFile | b64enc | quote }}
{{- end }}