{{- if .Values.auth0.createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth0.secretName }}
  labels:
    app.kubernetes.io/name: {{ include "auth0-exporter.name" . }}
    helm.sh/chart: {{ include "auth0-exporter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- if .Values.labels -}}
    {{- .Values.labels | toYaml | nindent 4 }}
    {{- end }}
type: Opaque
data:
  token: {{ .Values.auth0.token | b64enc}}
{{- end -}}